engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
exclude_paths:
- test/cases
- examples